# This is the main config file for SimpleSurvival
# Here you'll find customization options for every aspect of the plugin
# Make sure that you follow the proper formatting for config
Fly_Enabled: "&eFly Has Been Enabled"
Fly_Disabled: "&cFly Has Been Disabled"
Not_Player: "&cSorry, you must be a player to do this"
No_Permission: "&cSorry you do not have permission"
Join_Message: "&8[&e+&8]&e %player_name% has joined the server!"
Quit_Message: "&8[&e+&8]&e %player_name% has left the server!"
Scoreboard_Title: "&a[Test Server]"