Fly_Enabled: "&eFly Has Been Enabled"
Fly_Disabled: "&cFly Has Been Disabled"
Not_Player: "&cSorry, you must be a player to do this"
No_Permission: "&cSorry you do not have permission"
Join_Message: "&8[&e+&8]&e %player% has joined the server!"
Quit_Message: "&8[&e+&8]&e %player% has left the server!"
