name: SimpleSurvival
main: me.alexander.SimpleSurvival
version: 0.1.0
author: Alexander Milanovich
depend: [ProtocolLib]
softdepend: [PlaceholderAPI]
api-version: 1.13

commands:
  fly:
    usage: /<command>
    description: By doing this command, you can make yourself fly or others fly
  setspawn:
    usage: /<command>
    description: Use this command to set the world spawn
  spawn:
    usage: /<command>
    description: Use this command to teleport to spawn
  playerlist:
    aliases: [list]
    usage: /<command>
    description: This command will show you a list of players in a gui
  screload:
    usage: /<command>
    description: Reload config



