name: SimpleSurvival
main: me.alexander.SimpleSurvival
version: 0.1.0
author: Alexander Milanovich
depend: [Vault]

commands:
  fly:
    usage: /<command>
    description: Fly
  setspawn:
    usage: /<command>
    description: setspawn
  balance:
    usage: /<command>
    description: setspawn


